/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the overall health of the dashboard backend and a per-subsystem status map. A subsystem is True when it is reachable/valid, False when degraded.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all agents
         * @description Discover all configured OpenClaw agents from the filesystem and openclaw.json.  Returns summary information including status and last activity.
         */
        get: operations["list_agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get agent detail
         * @description Return full detail for a single agent including workspace path, file list, last activity, and status.
         */
        get: operations["get_agent_api_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read agent workspace file
         * @description Read a file from an agent's workspace.  The file path is passed as a query parameter (not a URL path segment).  Returns the file content plus an ETag header for concurrency control on subsequent writes.
         */
        get: operations["read_agent_file_api_agents__agent_id__files_get"];
        /**
         * Write agent workspace file
         * @description Write content to a file in an agent's workspace.  Requires an If-Match header containing the ETag returned by the GET request.  Returns 409 Conflict if the file was modified since it was last read.
         */
        put: operations["write_agent_file_api_agents__agent_id__files_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read OpenClaw configuration
         * @description Return the full openclaw.json with secret values redacted.  The response includes an ETag that must be passed as If-Match on subsequent write requests to prevent overwrite conflicts.
         */
        get: operations["get_config_api_config_get"];
        /**
         * Write OpenClaw configuration
         * @description Overwrite openclaw.json with the supplied config.  Requires an If-Match header with the ETag from the last GET.  Creates a timestamped backup before writing; keeps at most 10 backups.  Values sent as __REDACTED__ are preserved from the original file.
         */
        put: operations["put_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate configuration without saving
         * @description Validate a configuration JSON object against known rules.  Does not write to disk.  Returns a list of errors and warnings.
         */
        post: operations["validate_config_api_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gateway/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get gateway status
         * @description Run ``openclaw gateway status`` and return parsed status.  Returns a degraded response (running=False, error=...) if the CLI is unavailable or output cannot be parsed.
         */
        get: operations["get_gateway_status_api_gateway_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gateway/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a gateway command
         * @description Run start, stop, or restart on the OpenClaw gateway daemon.  The action is validated against the GatewayAction enum before the subprocess is executed — no shell interpolation occurs.
         */
        post: operations["gateway_command_api_gateway__action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentDetailResponse
         * @description Detailed agent information including workspace files.
         * @example {
         *       "files": [
         *         {
         *           "mtime": "2026-02-25T05:53:00Z",
         *           "name": "AGENTS.md",
         *           "size": 12400
         *         },
         *         {
         *           "mtime": "2026-02-25T05:55:00Z",
         *           "name": "SOUL.md",
         *           "size": 3800
         *         }
         *       ],
         *       "id": "main",
         *       "last_activity": "2026-02-25T05:54:00Z",
         *       "model": "anthropic/claude-opus-4-6",
         *       "name": "COS",
         *       "status": "active",
         *       "workspace": "/Users/miller/.openclaw/workspace"
         *     }
         */
        AgentDetailResponse: {
            /**
             * Id
             * @description Unique agent identifier
             */
            id: string;
            /**
             * Name
             * @description Agent display name
             */
            name: string;
            /**
             * Model
             * @description Model being used
             */
            model: string;
            /**
             * Workspace
             * @description Path to agent workspace
             */
            workspace: string;
            /**
             * Files
             * @description List of files in workspace
             */
            files?: components["schemas"]["AgentFileInfo"][];
            /**
             * Last Activity
             * @description Last activity timestamp
             */
            last_activity?: string | null;
            /**
             * Status
             * @description Agent status: active, idle, stopped
             */
            status: string;
        };
        /**
         * AgentFileInfo
         * @description Information about a file in an agent's workspace.
         * @example {
         *       "mtime": "2026-02-25T05:53:00Z",
         *       "name": "AGENTS.md",
         *       "size": 12400
         *     }
         */
        AgentFileInfo: {
            /**
             * Name
             * @description File name
             */
            name: string;
            /**
             * Size
             * @description File size in bytes
             */
            size: number;
            /**
             * Mtime
             * Format: date-time
             * @description Last modified timestamp
             */
            mtime: string;
        };
        /**
         * AgentListResponse
         * @description Response containing list of all agents.
         * @example {
         *       "agents": [
         *         {
         *           "id": "main",
         *           "last_activity": "2026-02-25T05:54:00Z",
         *           "model": "anthropic/claude-opus-4-6",
         *           "name": "COS",
         *           "status": "active"
         *         },
         *         {
         *           "id": "coder",
         *           "last_activity": "2026-02-25T04:30:00Z",
         *           "model": "anthropic/claude-sonnet-4-6",
         *           "name": "Coder",
         *           "status": "idle"
         *         }
         *       ],
         *       "total": 2
         *     }
         */
        AgentListResponse: {
            /**
             * Agents
             * @description List of agent summaries
             */
            agents: components["schemas"]["AgentSummary"][];
            /**
             * Total
             * @description Total number of agents
             */
            total: number;
        };
        /**
         * AgentSummary
         * @description Summary information about an agent.
         * @example {
         *       "id": "main",
         *       "last_activity": "2026-02-25T05:54:00Z",
         *       "model": "anthropic/claude-opus-4-6",
         *       "name": "COS",
         *       "status": "active"
         *     }
         */
        AgentSummary: {
            /**
             * Id
             * @description Unique agent identifier
             */
            id: string;
            /**
             * Name
             * @description Agent display name
             */
            name: string;
            /**
             * Model
             * @description Model being used
             */
            model: string;
            /**
             * Status
             * @description Agent status: active, idle, stopped
             */
            status: string;
            /**
             * Last Activity
             * @description Last activity timestamp
             */
            last_activity?: string | null;
        };
        /**
         * CommandResponse
         * @description Response from a gateway command.
         * @example {
         *       "action": "restart",
         *       "message": "Gateway restarted successfully",
         *       "output": "Gateway stopped.\nGateway started.",
         *       "success": true
         *     }
         */
        CommandResponse: {
            /**
             * Success
             * @description Whether the command succeeded
             */
            success: boolean;
            /** @description Action that was performed */
            action: components["schemas"]["GatewayAction"];
            /**
             * Message
             * @description Human-readable response message
             */
            message: string;
            /**
             * Output
             * @description Command output if available
             */
            output?: string | null;
        };
        /**
         * ConfigResponse
         * @description Response containing OpenClaw configuration (secrets redacted).
         * @example {
         *       "config": {
         *         "agents": {
         *           "main": {
         *             "model": "anthropic/claude-opus-4-6",
         *             "workspace": "workspace"
         *           }
         *         },
         *         "gateway": {
         *           "port": 8400
         *         }
         *       },
         *       "etag": "1708840800:2048",
         *       "path": "/Users/miller/.openclaw/openclaw.json"
         *     }
         */
        ConfigResponse: {
            /**
             * Config
             * @description OpenClaw configuration object
             */
            config: {
                [key: string]: unknown;
            };
            /**
             * Etag
             * @description ETag for concurrency control
             */
            etag: string;
            /**
             * Path
             * @description Path to config file
             */
            path: string;
        };
        /**
         * ConfigValidateResponse
         * @description Response from validating configuration.
         * @example {
         *       "errors": [],
         *       "valid": true,
         *       "warnings": [
         *         "Default workspace path may not exist"
         *       ]
         *     }
         */
        ConfigValidateResponse: {
            /**
             * Valid
             * @description Whether the configuration is valid
             */
            valid: boolean;
            /**
             * Errors
             * @description List of validation errors
             */
            errors?: string[];
            /**
             * Warnings
             * @description List of validation warnings
             */
            warnings?: string[];
        };
        /**
         * ConfigWriteRequest
         * @description Request body for writing configuration.
         * @example {
         *       "config": {
         *         "agents": {
         *           "main": {
         *             "model": "anthropic/claude-opus-4-6"
         *           }
         *         }
         *       },
         *       "etag": "1708840800:2048"
         *     }
         */
        ConfigWriteRequest: {
            /**
             * Config
             * @description Configuration object to save
             */
            config: {
                [key: string]: unknown;
            };
            /**
             * Etag
             * @description ETag for concurrency control
             */
            etag?: string | null;
        };
        /**
         * FileContentResponse
         * @description Response containing file content with metadata.
         * @example {
         *       "content": "# AGENTS.md - Your Workspace\n...",
         *       "language": "markdown",
         *       "mtime": "2026-02-25T05:53:00Z",
         *       "path": "AGENTS.md",
         *       "size": 12400
         *     }
         */
        FileContentResponse: {
            /**
             * Path
             * @description File path relative to workspace
             */
            path: string;
            /**
             * Content
             * @description File content
             */
            content: string;
            /**
             * Size
             * @description File size in bytes
             */
            size: number;
            /**
             * Mtime
             * Format: date-time
             * @description Last modified timestamp
             */
            mtime: string;
            /**
             * Language
             * @description Detected language for syntax highlighting
             */
            language: string;
        };
        /**
         * GatewayAction
         * @description Valid gateway actions - enum validated server-side.
         * @enum {string}
         */
        GatewayAction: "start" | "stop" | "restart";
        /**
         * GatewayStatusResponse
         * @description Response containing gateway status information.
         * @example {
         *       "channels": {},
         *       "pid": 12345,
         *       "running": true,
         *       "uptime": "2h 15m"
         *     }
         */
        GatewayStatusResponse: {
            /**
             * Running
             * @description Whether the gateway is running
             */
            running: boolean;
            /**
             * Pid
             * @description Gateway process ID if running
             */
            pid?: number | null;
            /**
             * Uptime
             * @description Gateway uptime string
             */
            uptime?: string | null;
            /**
             * Channels
             * @description Active channels
             */
            channels?: {
                [key: string]: unknown;
            };
            /**
             * Error
             * @description Error message if status unknown
             */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         * @example {
         *       "openclaw_home": "/Users/miller/.openclaw",
         *       "status": "ok",
         *       "subsystems": {
         *         "config": true,
         *         "gateway_cli": true,
         *         "sessions": true,
         *         "workspaces": true
         *       },
         *       "version": "1.0.0"
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @description Overall health status
             */
            status: string;
            /**
             * Version
             * @description Application version
             */
            version: string;
            /**
             * Openclaw Home
             * @description Path to OpenClaw home directory
             */
            openclaw_home: string;
            /**
             * Subsystems
             * @description Status of each subsystem
             */
            subsystems: {
                [key: string]: unknown;
            };
        };
        /**
         * SaveResponse
         * @description Response after successful file save.
         * @example {
         *       "etag": "1708840800:12450",
         *       "mtime": "2026-02-25T06:00:00Z",
         *       "path": "AGENTS.md",
         *       "size": 12450
         *     }
         */
        SaveResponse: {
            /**
             * Path
             * @description File path that was saved
             */
            path: string;
            /**
             * Size
             * @description New file size in bytes
             */
            size: number;
            /**
             * Mtime
             * Format: date-time
             * @description New modified timestamp
             */
            mtime: string;
            /**
             * Etag
             * @description New ETag for the saved file
             */
            etag: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListResponse"];
                };
            };
        };
    };
    get_agent_api_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetailResponse"];
                };
            };
            /** @description Agent or workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_agent_file_api_agents__agent_id__files_get: {
        parameters: {
            query: {
                /** @description File path relative to the agent's workspace */
                path: string;
            };
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContentResponse"];
                };
            };
            /** @description Path outside sandbox */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_agent_file_api_agents__agent_id__files_put: {
        parameters: {
            query: {
                /** @description File path relative to the agent's workspace */
                path: string;
            };
            header?: {
                /** @description ETag from last GET */
                "if-match"?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Path outside sandbox or read-only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Agent workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ETag mismatch — file changed externally */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description openclaw.json not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_config_api_config_put: {
        parameters: {
            query?: never;
            header?: {
                /** @description ETag from last GET */
                "if-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description ETag mismatch — file changed externally */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validate_config_api_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gateway_status_api_gateway_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayStatusResponse"];
                };
            };
        };
    };
    gateway_command_api_gateway__action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: components["schemas"]["GatewayAction"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Invalid action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway command timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
